version: "3.8"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  app:
    image: task-runner-service
    build: .
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
    ports:
      - "8080:8080"
